name: Build Staging App
on:
  workflow_dispatch:
    inputs:
      app-version:
        description: 'Application version (Commit hash)'
        required: true
        default: 'latest'

jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code into specific application versoin
      run: |
        echo === ${{ github.actor }} ===
        echo ${{ github.event.inputs.app-version }} > /tmp/app.txt
        ls -l /tmp
