name: Build Staging App 2
on: 
  workflow_dispatch:
    inputs:
      app-version:
        description: 'Application version (Commit hash)'
        required: true
        default: 'latest'

jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: |
        base64 -w 0 < $GITHUB_ENV
